// LOGIN 
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';
export const LOGIN_AUTHORIZED = 'LOGIN_AUTHORIZED';
export const LOGOUT = 'LOGOUT';
export const SET_CURRENT_USER_START = 'SET_CURRENT_USER_START';
export const SET_CURRENT_USER_FULFILLED = 'SET_CURRENT_USER_FULFILLED';
export const SET_CURRENT_USER_REJECTED = 'SET_CURRENT_USER_REJECTED';

// FETCH USERS
export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_FULFILLED = 'FETCH_USERS_FULFILLED';
export const FETCH_USERS_REJECTED = 'FETCH_USERS_REJECTED';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';